services:
  api1:
    build: .
    command: ["./main", "9999"]
    ports:
      - 9999:9999
  api2:
    build: .
    command: ["./main", "9998"]
    ports:
      - 9998:9998
  api3:
    build: .
    command: ["./main", "9997"]
    ports:
      - 9997:9997
