services:
  api1:
    build: .
    command: ["./main"]
  api2:
    build: .
    command: ["./main"]
  api3:
    build: .
    command: ["./main"]

  load-balancer:
    image: nginx:1.29.0
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
